# Railway Multi-Service Configuration
# Candid Analytics Application

# API Service Configuration
[[services]]
name = "api"
source = "api"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"

[services.deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services.env]]
PORT = { default = "80" }

# Frontend Service Configuration
[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[services.deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services.env]]
PORT = { default = "5173" }
